In [1]:
import torch
import numpy as np

# 텐서(tensor) 초기화

데이터로 직접 생성하기

In [2]:
data = [[1,2], [3,4]]
x_data = torch.tensor(data)

NumPy 배열로 생성하기

In [3]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

**다른 텐서로 생성하기**


명시적으로 재정의(override)하지 않으면, 인자로 주어진 텐서의 속성(모양, 자료형)을 유지함

In [4]:
x_ones = torch.ones_like(x_data)
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float)
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.6188, 0.4089],
        [0.5802, 0.8417]]) 



난수(random) or 상수(constant) 사용하기

In [5]:
shape = (2, 3, )
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor} \n")

Random Tensor: 
 tensor([[0.4231, 0.6783, 0.8920],
        [0.2676, 0.1676, 0.1884]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]]) 



# 텐서의 속성(Arribute)
텐서의 속성은 텐서의 모양(shape), 자료형(datatype) 및 어느 장치에 저장되는지를 나타낸다.

In [6]:
tensor = torch.rand(3, 4)

print(f"Shape of Tensor: {tensor.shape}")
print(f"Datatype of Tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of Tensor: torch.Size([3, 4])
Datatype of Tensor: torch.float32
Device tensor is stored on: cpu


# 텐서 연산(Operation)

전치, 인덱싱, 슬라이싱, 수학 계산, 선형 대수, 임의 샘플링 등 100가지 이상의 연산

각 연산은 GPU에서 실행 가능

기본적으로 tensor는 CPU에 생성됨

`.to` 메서드를 사용하면 GPU로 텐서를 명시적으로 이동시킬 수 있음

장치들 간에 큰 tensor를 복사하는 것은 시간과 메모리 비용이 많이 듦!

In [7]:
# GPU가 존재하면 tensor를 이동시킴
if torch.cuda.is_available():
	tensor = tensor.to("cuda")

print(f"Device tensor is stored on: {tensor.device}")

Device tensor is stored on: cuda:0


**NumPy식의 표준 인덱싱과 슬라이싱**

In [8]:
tensor = torch.ones(4, 4)	# 1로 채워진 3*4 배열 생성
print(f"First row: {tensor[0]}")
print(f"First column: {tensor[:, 0]}")
print(f"Last column: {tensor[...,-1]}")
tensor[:, 1] = 0
print(tensor)

First row: tensor([1., 1., 1., 1.])
First column: tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


**텐서 합치기**


`torch.cat`을 사용해서 주어진 차원에 따라 tensor를 연결할 수 있음
`torch.cat`과 미묘하게 다른 텐서 결합 연산자(tensor joining operator)인 `torch.stack`도 있음

In [9]:
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


**산술 연산**

In [10]:
# 두 텐서 간 행렬 곱 계산
y1 = tensor @ tensor.T	# tensor.T: tensor의 전치 행렬
y2 = tensor.matmul(tensor.T)

y3 = torch.rand_like(y1)
torch.matmul(tensor, tensor.T, out=y3)

print(y1)
print(y2)
print(y3)

# 요소별 곱(element-wise product) 계산
z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

print(z1)
print(z2)
print(z3)

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])
tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])
tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


**단일 요소(single-element) 텐서**

텐서의 모든 값을 하나로 집계(aggregate)해서 요소가 하나인 텐서인 경우, 

`item()`을 사용하여 python 숫자값으로 변환 가능

In [11]:
agg = tensor.sum()
agg_item = agg.item()
print(agg)
print(agg_item, type(agg_item))

tensor(12.)
12.0 <class 'float'>


**바꿔치기(in-place) 연산**
연산 결과를 피연산자에 저장하는 연산

`_` 접미사를 가짐


ex. `x.copy_(y)`, `x.t_()`

메모리 일부를 절약하지만, 기록(history)이 즉시 삭제되어 도함수 계산에 문제가 발생할 수 있음.

사용 권장 x

In [12]:
print(f"{tensor}\n")
tensor.add_(5)
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


**NumPy 변환(Bridge)**

CPU 상의 텐서와 Numpy 배열은 메모리 공간을 공유하기 때문에, 하나를 변경하면 다른 하나도 변경됨

Tensor -> Numpy 배열

In [13]:
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


In [14]:
t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


Numpy 배열 -> Tensor

In [15]:
n = np.ones(5)
t = torch.from_numpy(n)

np.add(n, 1, out=n)
print(f"t: {t}")
print(f"n: {n}")

t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]
t: tensor([3., 3., 3., 3., 3.], dtype=torch.float64)
n: [3. 3. 3. 3. 3.]
